name: Project Submission
description: Submit your project
title: "[Project] <title>"
labels: [Project, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Did you attend the GitHub Workshop? 
    description: Please select ✅ if you have attended the GitHub Workshop
    options:
    - label: I have attended the GitHub Workshop
      required: true
- type: input
  attributes:
    label: Project Name
    description: Please add a name to your weekend project.
  validations:
    required: true
- type: input
  attributes:
    label: Project Repository
    description: Please share GitHub repository link of your project.
  validations:
    required: true
- type: input
  attributes:
    label: Project URL
    description: Please share demo link of your project or demo video.
  validations:
    required: true
- type: input
  attributes:
    label: University Name
    description: University Name
  validations:
    required: true
- type: textarea
  attributes:
    label: Project Description
    description: |
      Links? References? Anything that will give us more context about your project!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: dropdown
  attributes:
    label: GitHub Student Developer Pack Tools Used
    description: |
      Projects must use at least one tool from the Pack to be posted on the Student Gallery.
    options:
      - Deepsource
      - Deepscan
      - pyCharm
      - Push Bots
  validations:
    required: true
- type: dropdown
  attributes:
    label: What is your level of education?
    options:
      - College or University(2 Years)
      - College or University(4 Years)
      - Graduate
  validations:
    required: false
