name: Project Submission
description: Submit your project
title: "[Project] <title>"
labels: [Project, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Did you attend the GitHub Workshop? 
    description: Please select ✅ if you have attended the GitHub Workshop
    options:
    - label: I have attended the GitHub Workshop
      required: true
- type: input
  attributes:
    label: Project Name
    description: Please add a name to your weekend project.
  validations:
    required: true
- type: input
  attributes:
    label: Project Repository
    description: Please share GitHub repository link of your project.
  validations:
    required: true
- type: input
  attributes:
    label: Project URL
    description: Please share demo link of your project or demo video.
  validations:
    required: true
- type: dropdown
  attributes:
    label: University Name
    description: University Name
    options:
    options:
      - AAR Mahaveer Engineering College
      - Ajay Kumar Garg Engineering College
      - Amrita Vishwa Vidyapeetham
      - Assam Don Bosco University
      - Bangalore Institute of Technology (BIT)
      - Bharati Vidyapeeth's College of Engineering, New Delhi
      - BITS, Pilani - Hyderabad
      - Deenbandhu Chhotu Ram University of Science and Technology
      - Dronacharya College of Engineering
      - Dronacharya Group of Institutions Greater Noida
      - Er. Perumal Manimekalai College Of Engg
      - GITA Autonomous College
      - Haldia Institute of Technology
      - Hindustan University-Chennai
      - IIIT Vadodara
      - Indian Institute of Information Technology Tiruchirappalli
      - Indraprastha Institute of Information Technology, Delhi
      - Institute of Advanced Research
      - Institute of Engineering MET
      - International Institute of Information Technology, Naya Raipur
      - ISL Engineering College
      - Jodhpur Institute of Engineering and Technology
      - Kalasalingam University - Virudhunagar
      - Kumaun University Nainital
      - L.D. COLLEGE OF ENGINEERING
      - Lokmanya Tilak College of Engineering
      - Lovely Professional University, India
      - Madhav Institute of Technology
      - MEC Namakkal
      - MVN University
      - National Institute of Science and Technology
      - Rustamji Institute of Technology
      - Sengunthar Engineering College
      - Shri Guru Gobind Singhji Institute of Engineering and Technology
      - Shri Shankaracharya Technical Campus
      - Sikkim Manipal Institute of Technology
      - SJB Institute of Technology
      - Sreepathy Institute of Management And Technology
      - SRI VENKATESWARAA COLLEGE OF TECHNOLOGY
      - The National Institute of Engineering
  validations:
    required: true
- type: textarea
  attributes:
    label: Project Description
    description: |
      Links? References? Anything that will give us more context about your project!

      Tip: You can attach project details - pdf files, project presentation, images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: dropdown
  attributes:
    label: GitHub Student Developer Pack Tools Used
    description: |
      Projects must use at least one tool from the Pack.
    multiple: true
    options:
      - Deepsource
      - Deepscan
      - pyCharm
      - Push Bots
      - Canva
      - Microsoft Azure
      - GitHub
      - ATOM
      - Mongo DB
      - Twilio
      - Pop SQL
      - Astra
      - WiseJ
      - LogDNA
  validations:
    required: true
