name: Project Submission
description: Submit your project
title: "[Project] <title>"
labels: [Project, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Did you attend the GitHub Workshop? 
    description: Please select ✅ if you have attended the GitHub Workshop
    options:
    - label: I have attended the GitHub Workshop
      required: true
- type: input
  attributes:
    label: Project Name
    description: Please add a name to your weekend project.
  validations:
    required: true
- type: input
  attributes:
    label: Project Repository
    description: Please share GitHub repository link of your project.
  validations:
    required: true
- type: input
  attributes:
    label: Project URL
    description: Please share demo link of your project or demo video.
  validations:
    required: true
- type: dropdown
  attributes:
    label: University Name
    description: University Name
    options:
    - ABES institute of technology
    - The Assam Royal Global University
    - SCTR's Pune Institute of Computer Technology
    - KSR College of Engineering
    - Delhi Technical Campus
    - Don Bosco Institute of Technology, Mumbai
    - Jaypee University of Engineering and Technology
    - Babasaheb Bhimrao Ambedkar University
    - KCT Engineering College
    - International Institute of Professional Studies Devi Ahilya University, Indore
    - SIES GRADUATE SCHOOL OF TECHNOLOGY
    - PES College of Engineering, Mandya
    - Dr. Sudhir Chandra Sur Institute of Technology
    - JAIN
    - Heritage Institute of Technology, Kolkata
    - Kerala University of Digital Sciences, Innovation and Technology
    - Invertis University Bareilly
    - Sardar Vallabhbhai Patel Institute of Technology, Vasad
    - Masai School
    - Assam Engineering College
    - Santhiram Engineering College
    - CHRIST (Deemed to be University)
    - SreeVidyanikethan Engineering College
    - PSG College of Technology
    - Chandigarh College of Engineering
    - Indian Institute of Technology Ropar
    - Government College of Engineering Srirangam, Thiruchirapalli
    - Sanskar Institute of Management and Information Technology
    - Maharaja Institute of Technology Mysore
  validations:
    required: true
- type: textarea
  attributes:
    label: Project Description
    description: |
      Links? References? Anything that will give us more context about your project!

      Tip: You can attach project details - pdf files, project presentation, images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: dropdown
  attributes:
    label: GitHub Student Developer Pack Tools Used
    description: |
      Projects must use at least one tool from the Pack.
    multiple: true
    options:
      - Deepsource
      - Deepscan
      - pyCharm
      - Push Bots
      - Canva
      - Microsoft Azure
      - GitHub
      - ATOM
      - Mongo DB
      - Twilio
      - Pop SQL
      - Astra
      - WiseJ
      - LogDNA
  validations:
    required: true
